module AlchemystAI
  module Models
    module V1
      module Context
        type view_retrieve_params =
          {  } & AlchemystAI::Internal::Type::request_parameters

        class ViewRetrieveParams < AlchemystAI::Internal::Type::BaseModel
          extend AlchemystAI::Internal::Type::RequestParameters::Converter
          include AlchemystAI::Internal::Type::RequestParameters

          def initialize: (?request_options: AlchemystAI::request_opts) -> void

          def to_hash: -> { request_options: AlchemystAI::RequestOptions }
        end
      end
    end
  end
end
