module Alchemystai
  module Resources
    class V1
      class Context
        attr_reader traces: Alchemystai::Resources::V1::Context::Traces

        attr_reader view: Alchemystai::Resources::V1::Context::View

        attr_reader memory: Alchemystai::Resources::V1::Context::Memory

        def delete: (
          organization_id: String,
          source: String,
          ?by_doc: bool?,
          ?by_id: bool?,
          ?user_id: String?,
          ?request_options: Alchemystai::request_opts
        ) -> top

        def add: (
          context_type: Alchemystai::Models::V1::ContextAddParams::context_type,
          documents: ::Array[Alchemystai::V1::ContextAddParams::Document],
          scope: Alchemystai::Models::V1::ContextAddParams::scope,
          source: String,
          ?metadata: Alchemystai::V1::ContextAddParams::Metadata,
          ?request_options: Alchemystai::request_opts
        ) -> Alchemystai::Models::V1::ContextAddResponse

        def initialize: (client: Alchemystai::Client) -> void
      end
    end
  end
end
