module AlchemystAISDK
  module Models
    module V1
      module Context
        type memory_add_params =
          {
            contents: ::Array[AlchemystAISDK::V1::Context::MemoryAddParams::Content],
            memory_id: String
          }
          & AlchemystAISDK::Internal::Type::request_parameters

        class MemoryAddParams < AlchemystAISDK::Internal::Type::BaseModel
          extend AlchemystAISDK::Internal::Type::RequestParameters::Converter
          include AlchemystAISDK::Internal::Type::RequestParameters

          attr_reader contents: ::Array[AlchemystAISDK::V1::Context::MemoryAddParams::Content]?

          def contents=: (
            ::Array[AlchemystAISDK::V1::Context::MemoryAddParams::Content]
          ) -> ::Array[AlchemystAISDK::V1::Context::MemoryAddParams::Content]

          attr_reader memory_id: String?

          def memory_id=: (String) -> String

          def initialize: (
            ?contents: ::Array[AlchemystAISDK::V1::Context::MemoryAddParams::Content],
            ?memory_id: String,
            ?request_options: AlchemystAISDK::request_opts
          ) -> void

          def to_hash: -> {
            contents: ::Array[AlchemystAISDK::V1::Context::MemoryAddParams::Content],
            memory_id: String,
            request_options: AlchemystAISDK::RequestOptions
          }

          type content = { content: String }

          class Content < AlchemystAISDK::Internal::Type::BaseModel
            attr_reader content: String?

            def content=: (String) -> String

            def initialize: (?content: String) -> void

            def to_hash: -> { content: String }
          end
        end
      end
    end
  end
end
