module AlchemystAISDK
  module Models
    module V1
      module Context
        type view_retrieve_response = { context: ::Array[top] }

        class ViewRetrieveResponse < AlchemystAISDK::Internal::Type::BaseModel
          attr_reader context: ::Array[top]?

          def context=: (::Array[top]) -> ::Array[top]

          def initialize: (?context: ::Array[top]) -> void

          def to_hash: -> { context: ::Array[top] }
        end
      end
    end
  end
end
