module Alchemystai
  module Resources
    class V1
      class Context
        class Memory
          def delete: (
            ?memory_id: String,
            ?organization_id: String?,
            ?user_id: String?,
            ?request_options: Alchemystai::request_opts
          ) -> nil

          def add: (
            ?contents: ::Array[Alchemystai::V1::Context::MemoryAddParams::Content],
            ?memory_id: String,
            ?request_options: Alchemystai::request_opts
          ) -> nil

          def initialize: (client: Alchemystai::Client) -> void
        end
      end
    end
  end
end
