module AlchemystAI
  module Models
    module V1
      type context_delete_params =
        {
          by_doc: bool?,
          by_id: bool?,
          organization_id: String?,
          source: String,
          user_id: String?
        }
        & AlchemystAI::Internal::Type::request_parameters

      class ContextDeleteParams < AlchemystAI::Internal::Type::BaseModel
        extend AlchemystAI::Internal::Type::RequestParameters::Converter
        include AlchemystAI::Internal::Type::RequestParameters

        attr_accessor by_doc: bool?

        attr_accessor by_id: bool?

        attr_accessor organization_id: String?

        attr_reader source: String?

        def source=: (String) -> String

        attr_accessor user_id: String?

        def initialize: (
          ?by_doc: bool?,
          ?by_id: bool?,
          ?organization_id: String?,
          ?source: String,
          ?user_id: String?,
          ?request_options: AlchemystAI::request_opts
        ) -> void

        def to_hash: -> {
          by_doc: bool?,
          by_id: bool?,
          organization_id: String?,
          source: String,
          user_id: String?,
          request_options: AlchemystAI::RequestOptions
        }
      end
    end
  end
end
