module AlchemystAISDK
  module Models
    module V1
      type context_search_params =
        {
          minimum_similarity_threshold: Float,
          query: String,
          similarity_threshold: Float,
          metadata: top,
          scope: AlchemystAISDK::Models::V1::ContextSearchParams::scope,
          user_id: String
        }
        & AlchemystAISDK::Internal::Type::request_parameters

      class ContextSearchParams < AlchemystAISDK::Internal::Type::BaseModel
        extend AlchemystAISDK::Internal::Type::RequestParameters::Converter
        include AlchemystAISDK::Internal::Type::RequestParameters

        attr_accessor minimum_similarity_threshold: Float

        attr_accessor query: String

        attr_accessor similarity_threshold: Float

        attr_reader metadata: top?

        def metadata=: (top) -> top

        attr_reader scope: AlchemystAISDK::Models::V1::ContextSearchParams::scope?

        def scope=: (
          AlchemystAISDK::Models::V1::ContextSearchParams::scope
        ) -> AlchemystAISDK::Models::V1::ContextSearchParams::scope

        attr_reader user_id: String?

        def user_id=: (String) -> String

        def initialize: (
          minimum_similarity_threshold: Float,
          query: String,
          similarity_threshold: Float,
          ?metadata: top,
          ?scope: AlchemystAISDK::Models::V1::ContextSearchParams::scope,
          ?user_id: String,
          ?request_options: AlchemystAISDK::request_opts
        ) -> void

        def to_hash: -> {
          minimum_similarity_threshold: Float,
          query: String,
          similarity_threshold: Float,
          metadata: top,
          scope: AlchemystAISDK::Models::V1::ContextSearchParams::scope,
          user_id: String,
          request_options: AlchemystAISDK::RequestOptions
        }

        type scope = :internal | :external

        module Scope
          extend AlchemystAISDK::Internal::Type::Enum

          INTERNAL: :internal
          EXTERNAL: :external

          def self?.values: -> ::Array[AlchemystAISDK::Models::V1::ContextSearchParams::scope]
        end
      end
    end
  end
end
