module AlchemystAISDK
  module Models
    module V1
      type context_search_response =
        {
          contexts: ::Array[AlchemystAISDK::Models::V1::ContextSearchResponse::Context]
        }

      class ContextSearchResponse < AlchemystAISDK::Internal::Type::BaseModel
        attr_reader contexts: ::Array[AlchemystAISDK::Models::V1::ContextSearchResponse::Context]?

        def contexts=: (
          ::Array[AlchemystAISDK::Models::V1::ContextSearchResponse::Context]
        ) -> ::Array[AlchemystAISDK::Models::V1::ContextSearchResponse::Context]

        def initialize: (
          ?contexts: ::Array[AlchemystAISDK::Models::V1::ContextSearchResponse::Context]
        ) -> void

        def to_hash: -> {
          contexts: ::Array[AlchemystAISDK::Models::V1::ContextSearchResponse::Context]
        }

        type context =
          {
            content: String,
            created_at: Time,
            metadata: top,
            score: Float,
            updated_at: Time
          }

        class Context < AlchemystAISDK::Internal::Type::BaseModel
          attr_reader content: String?

          def content=: (String) -> String

          attr_reader created_at: Time?

          def created_at=: (Time) -> Time

          attr_reader metadata: top?

          def metadata=: (top) -> top

          attr_reader score: Float?

          def score=: (Float) -> Float

          attr_reader updated_at: Time?

          def updated_at=: (Time) -> Time

          def initialize: (
            ?content: String,
            ?created_at: Time,
            ?metadata: top,
            ?score: Float,
            ?updated_at: Time
          ) -> void

          def to_hash: -> {
            content: String,
            created_at: Time,
            metadata: top,
            score: Float,
            updated_at: Time
          }
        end
      end
    end
  end
end
