module AlchemystAISDK
  module Models
    module V1
      type context_add_params =
        {
          context_type: AlchemystAISDK::Models::V1::ContextAddParams::context_type,
          documents: ::Array[AlchemystAISDK::V1::ContextAddParams::Document],
          metadata: AlchemystAISDK::V1::ContextAddParams::Metadata,
          scope: AlchemystAISDK::Models::V1::ContextAddParams::scope,
          source: String
        }
        & AlchemystAISDK::Internal::Type::request_parameters

      class ContextAddParams < AlchemystAISDK::Internal::Type::BaseModel
        extend AlchemystAISDK::Internal::Type::RequestParameters::Converter
        include AlchemystAISDK::Internal::Type::RequestParameters

        attr_reader context_type: AlchemystAISDK::Models::V1::ContextAddParams::context_type?

        def context_type=: (
          AlchemystAISDK::Models::V1::ContextAddParams::context_type
        ) -> AlchemystAISDK::Models::V1::ContextAddParams::context_type

        attr_reader documents: ::Array[AlchemystAISDK::V1::ContextAddParams::Document]?

        def documents=: (
          ::Array[AlchemystAISDK::V1::ContextAddParams::Document]
        ) -> ::Array[AlchemystAISDK::V1::ContextAddParams::Document]

        attr_reader metadata: AlchemystAISDK::V1::ContextAddParams::Metadata?

        def metadata=: (
          AlchemystAISDK::V1::ContextAddParams::Metadata
        ) -> AlchemystAISDK::V1::ContextAddParams::Metadata

        attr_reader scope: AlchemystAISDK::Models::V1::ContextAddParams::scope?

        def scope=: (
          AlchemystAISDK::Models::V1::ContextAddParams::scope
        ) -> AlchemystAISDK::Models::V1::ContextAddParams::scope

        attr_reader source: String?

        def source=: (String) -> String

        def initialize: (
          ?context_type: AlchemystAISDK::Models::V1::ContextAddParams::context_type,
          ?documents: ::Array[AlchemystAISDK::V1::ContextAddParams::Document],
          ?metadata: AlchemystAISDK::V1::ContextAddParams::Metadata,
          ?scope: AlchemystAISDK::Models::V1::ContextAddParams::scope,
          ?source: String,
          ?request_options: AlchemystAISDK::request_opts
        ) -> void

        def to_hash: -> {
          context_type: AlchemystAISDK::Models::V1::ContextAddParams::context_type,
          documents: ::Array[AlchemystAISDK::V1::ContextAddParams::Document],
          metadata: AlchemystAISDK::V1::ContextAddParams::Metadata,
          scope: AlchemystAISDK::Models::V1::ContextAddParams::scope,
          source: String,
          request_options: AlchemystAISDK::RequestOptions
        }

        type context_type = :resource | :conversation | :instruction

        module ContextType
          extend AlchemystAISDK::Internal::Type::Enum

          RESOURCE: :resource
          CONVERSATION: :conversation
          INSTRUCTION: :instruction

          def self?.values: -> ::Array[AlchemystAISDK::Models::V1::ContextAddParams::context_type]
        end

        type document = { content: String }

        class Document < AlchemystAISDK::Internal::Type::BaseModel
          attr_reader content: String?

          def content=: (String) -> String

          def initialize: (?content: String) -> void

          def to_hash: -> { content: String }
        end

        type metadata =
          {
            file_name: String,
            file_size: Float,
            file_type: String,
            group_name: ::Array[String],
            last_modified: String
          }

        class Metadata < AlchemystAISDK::Internal::Type::BaseModel
          attr_reader file_name: String?

          def file_name=: (String) -> String

          attr_reader file_size: Float?

          def file_size=: (Float) -> Float

          attr_reader file_type: String?

          def file_type=: (String) -> String

          attr_reader group_name: ::Array[String]?

          def group_name=: (::Array[String]) -> ::Array[String]

          attr_reader last_modified: String?

          def last_modified=: (String) -> String

          def initialize: (
            ?file_name: String,
            ?file_size: Float,
            ?file_type: String,
            ?group_name: ::Array[String],
            ?last_modified: String
          ) -> void

          def to_hash: -> {
            file_name: String,
            file_size: Float,
            file_type: String,
            group_name: ::Array[String],
            last_modified: String
          }
        end

        type scope = :internal | :external

        module Scope
          extend AlchemystAISDK::Internal::Type::Enum

          INTERNAL: :internal
          EXTERNAL: :external

          def self?.values: -> ::Array[AlchemystAISDK::Models::V1::ContextAddParams::scope]
        end
      end
    end
  end
end
