module AlchemystAI
  module Resources
    class V1
      class Org
        class Context
          def view: (
            user_ids: ::Array[String],
            ?request_options: AlchemystAI::request_opts
          ) -> AlchemystAI::Models::V1::Org::ContextViewResponse

          def initialize: (client: AlchemystAI::Client) -> void
        end
      end
    end
  end
end
