module Alchemystai
  module Models
    module V1
      module Context
        type add_async_cancel_response =
          { job_id: String, message: String, status: String, success: bool }

        class AddAsyncCancelResponse < Alchemystai::Internal::Type::BaseModel
          attr_accessor job_id: String

          attr_accessor message: String

          attr_accessor status: String

          attr_accessor success: bool

          def initialize: (
            job_id: String,
            message: String,
            status: String,
            success: bool
          ) -> void

          def to_hash: -> {
            job_id: String,
            message: String,
            status: String,
            success: bool
          }
        end
      end
    end
  end
end
