module Alchemystai
  module Models
    module V1
      module Context
        type memory_delete_params =
          {
            memory_id: String,
            organization_id: String?,
            by_doc: bool?,
            by_id: bool?,
            user_id: String?
          }
          & Alchemystai::Internal::Type::request_parameters

        class MemoryDeleteParams < Alchemystai::Internal::Type::BaseModel
          extend Alchemystai::Internal::Type::RequestParameters::Converter
          include Alchemystai::Internal::Type::RequestParameters

          attr_accessor memory_id: String

          attr_accessor organization_id: String?

          attr_accessor by_doc: bool?

          attr_accessor by_id: bool?

          attr_accessor user_id: String?

          def initialize: (
            memory_id: String,
            organization_id: String?,
            ?by_doc: bool?,
            ?by_id: bool?,
            ?user_id: String?,
            ?request_options: Alchemystai::request_opts
          ) -> void

          def to_hash: -> {
            memory_id: String,
            organization_id: String?,
            by_doc: bool?,
            by_id: bool?,
            user_id: String?,
            request_options: Alchemystai::RequestOptions
          }
        end
      end
    end
  end
end
