module Alchemystai
  module Models
    module V1
      module Context
        type memory_add_params =
          {
            contents: ::Array[Alchemystai::V1::Context::MemoryAddParams::Content],
            memory_id: String
          }
          & Alchemystai::Internal::Type::request_parameters

        class MemoryAddParams < Alchemystai::Internal::Type::BaseModel
          extend Alchemystai::Internal::Type::RequestParameters::Converter
          include Alchemystai::Internal::Type::RequestParameters

          attr_accessor contents: ::Array[Alchemystai::V1::Context::MemoryAddParams::Content]

          attr_accessor memory_id: String

          def initialize: (
            contents: ::Array[Alchemystai::V1::Context::MemoryAddParams::Content],
            memory_id: String,
            ?request_options: Alchemystai::request_opts
          ) -> void

          def to_hash: -> {
            contents: ::Array[Alchemystai::V1::Context::MemoryAddParams::Content],
            memory_id: String,
            request_options: Alchemystai::RequestOptions
          }

          type content =
            {
              id: String,
              content: String,
              created_at: String,
              metadata: ::Hash[Symbol, top],
              role: String
            }

          class Content < Alchemystai::Internal::Type::BaseModel
            attr_reader id: String?

            def id=: (String) -> String

            attr_reader content: String?

            def content=: (String) -> String

            attr_reader created_at: String?

            def created_at=: (String) -> String

            attr_reader metadata: ::Hash[Symbol, top]?

            def metadata=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

            attr_reader role: String?

            def role=: (String) -> String

            def initialize: (
              ?id: String,
              ?content: String,
              ?created_at: String,
              ?metadata: ::Hash[Symbol, top],
              ?role: String
            ) -> void

            def to_hash: -> {
              id: String,
              content: String,
              created_at: String,
              metadata: ::Hash[Symbol, top],
              role: String
            }
          end
        end
      end
    end
  end
end
