module Alchemystai
  module Models
    module V1
      module Context
        type memory_delete_params =
          { memory_id: String, organization_id: String?, user_id: String? }
          & Alchemystai::Internal::Type::request_parameters

        class MemoryDeleteParams < Alchemystai::Internal::Type::BaseModel
          extend Alchemystai::Internal::Type::RequestParameters::Converter
          include Alchemystai::Internal::Type::RequestParameters

          attr_reader memory_id: String?

          def memory_id=: (String) -> String

          attr_accessor organization_id: String?

          attr_accessor user_id: String?

          def initialize: (
            ?memory_id: String,
            ?organization_id: String?,
            ?user_id: String?,
            ?request_options: Alchemystai::request_opts
          ) -> void

          def to_hash: -> {
            memory_id: String,
            organization_id: String?,
            user_id: String?,
            request_options: Alchemystai::RequestOptions
          }
        end
      end
    end
  end
end
