module Alchemystai
  module Models
    module V1
      module Context
        type trace_list_params =
          { limit: Integer, page: Integer }
          & Alchemystai::Internal::Type::request_parameters

        class TraceListParams < Alchemystai::Internal::Type::BaseModel
          extend Alchemystai::Internal::Type::RequestParameters::Converter
          include Alchemystai::Internal::Type::RequestParameters

          attr_reader limit: Integer?

          def limit=: (Integer) -> Integer

          attr_reader page: Integer?

          def page=: (Integer) -> Integer

          def initialize: (
            ?limit: Integer,
            ?page: Integer,
            ?request_options: Alchemystai::request_opts
          ) -> void

          def to_hash: -> {
            limit: Integer,
            page: Integer,
            request_options: Alchemystai::RequestOptions
          }
        end
      end
    end
  end
end
