module Alchemystai
  module Models
    module V1
      module Context
        type view_retrieve_params =
          { file_name: String, magic_key: String }
          & Alchemystai::Internal::Type::request_parameters

        class ViewRetrieveParams < Alchemystai::Internal::Type::BaseModel
          extend Alchemystai::Internal::Type::RequestParameters::Converter
          include Alchemystai::Internal::Type::RequestParameters

          attr_reader file_name: String?

          def file_name=: (String) -> String

          attr_reader magic_key: String?

          def magic_key=: (String) -> String

          def initialize: (
            ?file_name: String,
            ?magic_key: String,
            ?request_options: Alchemystai::request_opts
          ) -> void

          def to_hash: -> {
            file_name: String,
            magic_key: String,
            request_options: Alchemystai::RequestOptions
          }
        end
      end
    end
  end
end
