module Alchemystai
  module Models
    module V1
      module Context
        type view_docs_params =
          { magic_key: String }
          & Alchemystai::Internal::Type::request_parameters

        class ViewDocsParams < Alchemystai::Internal::Type::BaseModel
          extend Alchemystai::Internal::Type::RequestParameters::Converter
          include Alchemystai::Internal::Type::RequestParameters

          attr_reader magic_key: String?

          def magic_key=: (String) -> String

          def initialize: (
            ?magic_key: String,
            ?request_options: Alchemystai::request_opts
          ) -> void

          def to_hash: -> {
            magic_key: String,
            request_options: Alchemystai::RequestOptions
          }
        end
      end
    end
  end
end
