module Alchemystai
  module Models
    module V1
      type context_search_params =
        {
          minimum_similarity_threshold: Float,
          query: String,
          similarity_threshold: Float,
          metadata: Alchemystai::Models::V1::ContextSearchParams::metadata,
          mode: Alchemystai::Models::V1::ContextSearchParams::mode,
          body_metadata: top,
          scope: Alchemystai::Models::V1::ContextSearchParams::scope,
          user_id: String
        }
        & Alchemystai::Internal::Type::request_parameters

      class ContextSearchParams < Alchemystai::Internal::Type::BaseModel
        extend Alchemystai::Internal::Type::RequestParameters::Converter
        include Alchemystai::Internal::Type::RequestParameters

        attr_accessor minimum_similarity_threshold: Float

        attr_accessor query: String

        attr_accessor similarity_threshold: Float

        attr_reader metadata: Alchemystai::Models::V1::ContextSearchParams::metadata?

        def metadata=: (
          Alchemystai::Models::V1::ContextSearchParams::metadata
        ) -> Alchemystai::Models::V1::ContextSearchParams::metadata

        attr_reader mode: Alchemystai::Models::V1::ContextSearchParams::mode?

        def mode=: (
          Alchemystai::Models::V1::ContextSearchParams::mode
        ) -> Alchemystai::Models::V1::ContextSearchParams::mode

        attr_reader body_metadata: top?

        def body_metadata=: (top) -> top

        attr_reader scope: Alchemystai::Models::V1::ContextSearchParams::scope?

        def scope=: (
          Alchemystai::Models::V1::ContextSearchParams::scope
        ) -> Alchemystai::Models::V1::ContextSearchParams::scope

        attr_reader user_id: String?

        def user_id=: (String) -> String

        def initialize: (
          minimum_similarity_threshold: Float,
          query: String,
          similarity_threshold: Float,
          ?metadata: Alchemystai::Models::V1::ContextSearchParams::metadata,
          ?mode: Alchemystai::Models::V1::ContextSearchParams::mode,
          ?body_metadata: top,
          ?scope: Alchemystai::Models::V1::ContextSearchParams::scope,
          ?user_id: String,
          ?request_options: Alchemystai::request_opts
        ) -> void

        def to_hash: -> {
          minimum_similarity_threshold: Float,
          query: String,
          similarity_threshold: Float,
          metadata: Alchemystai::Models::V1::ContextSearchParams::metadata,
          mode: Alchemystai::Models::V1::ContextSearchParams::mode,
          body_metadata: top,
          scope: Alchemystai::Models::V1::ContextSearchParams::scope,
          user_id: String,
          request_options: Alchemystai::RequestOptions
        }

        type metadata = :true | :false

        module Metadata
          extend Alchemystai::Internal::Type::Enum

          TRUE: :true
          FALSE: :false

          def self?.values: -> ::Array[Alchemystai::Models::V1::ContextSearchParams::metadata]
        end

        type mode = :fast | :standard

        module Mode
          extend Alchemystai::Internal::Type::Enum

          FAST: :fast
          STANDARD: :standard

          def self?.values: -> ::Array[Alchemystai::Models::V1::ContextSearchParams::mode]
        end

        type scope = :internal | :external

        module Scope
          extend Alchemystai::Internal::Type::Enum

          INTERNAL: :internal
          EXTERNAL: :external

          def self?.values: -> ::Array[Alchemystai::Models::V1::ContextSearchParams::scope]
        end
      end
    end
  end
end
