module Alchemystai
  module Resources
    class V1
      class Context
        class AddAsync
          class Status
            def retrieve: (
              String id,
              ?request_options: Alchemystai::request_opts
            ) -> Alchemystai::Models::V1::Context::AddAsync::StatusRetrieveResponse

            def list: (
              ?limit: String,
              ?offset: String,
              ?type: Alchemystai::Models::V1::Context::AddAsync::StatusListParams::type_,
              ?request_options: Alchemystai::request_opts
            ) -> Alchemystai::Models::V1::Context::AddAsync::StatusListResponse

            def initialize: (client: Alchemystai::Client) -> void
          end
        end
      end
    end
  end
end
